notifications:
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Diff: %{compare_url} Build: %{build_url}"
    channels:
      - "irc.freenode.net#makinacorpus-geotrek"
    skip_join: true

language: node_js

node_js:
  - '0.12'

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

cache:
  directories:
    - node_modules

script:
  - "npm i"
  - "npm test"
