notifications:
  irc:
    template:
      - "[%{repository_slug}] has been built: %{build_url} (%{result})"
      - "%{repository_name}/%{branch} %{commit} %{author}: %{message} (#%{build_number})"
    channels:
      - "irc.freenode.net#makinacorpus-geotrek"
    skip_join: true

language: node_js

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

cache:
  directories:
    - node_modules

install:
  - npm update

script:
  - "npm test"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
